#!/usr/bin/env bash
# =============================================================================
# IONE VPN – WireGuard Server Configuration Generator
# Run AFTER setup_server.sh on the droplet.
# =============================================================================
set -euo pipefail

WG_IF="wg0"
WG_DIR="/etc/wireguard"
# Port 443/udp: disguises WireGuard as HTTPS traffic, bypassing DPI firewalls
# that block non-standard UDP ports (common in hotels, airports, corporate nets).
WG_PORT="443"
SERVER_SUBNET="10.8.0.1/24"

GREEN='\033[0;32m'; NC='\033[0m'
info() { echo -e "${GREEN}[WG]${NC} $*"; }

# ─── Detect primary network interface ────────────────────────────────────────
ETH_IF=$(ip route | awk '/default/ {print $5; exit}')
info "Detected network interface: $ETH_IF"

# Ensure UFW forwarding policy allows VPN client egress traffic.
if [ -f /etc/default/ufw ]; then
  sed -i 's/^DEFAULT_FORWARD_POLICY=.*/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw || true
fi
ufw default allow routed || true
ufw allow "$WG_PORT/udp" || true   # WireGuard stealth port
ufw route allow in on "$WG_IF" out on "$ETH_IF" || true
ufw route allow in on "$ETH_IF" out on "$WG_IF" || true

# ─── Generate server keys ─────────────────────────────────────────────────────
if [ ! -f "$WG_DIR/privatekey" ]; then
  info "Generating WireGuard server key pair..."
  wg genkey | tee "$WG_DIR/privatekey" | wg pubkey > "$WG_DIR/publickey"
  chmod 600 "$WG_DIR/privatekey"
fi

SERVER_PRIVATE_KEY=$(cat "$WG_DIR/privatekey")
SERVER_PUBLIC_KEY=$(cat "$WG_DIR/publickey")

info "Server public key: $SERVER_PUBLIC_KEY"

# ─── Detect droplet public IP (try external service, fall back to interface) ──
DROPLET_IP=""
for url in "https://api.ipify.org" "https://ifconfig.me" "https://icanhazip.com"; do
  DROPLET_IP=$(curl -sf --max-time 5 "$url" || true)
  if [[ "$DROPLET_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    break
  fi
done
if [[ ! "$DROPLET_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  warn "Could not auto-detect public IP. Please enter it manually:"
  read -rp "Droplet public IPv4: " DROPLET_IP
fi
info "Droplet IP: $DROPLET_IP"

# ─── Write wg0.conf ──────────────────────────────────────────────────────────
# Enable kernel IP forwarding now and persist across reboots.
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=1
cat >/etc/sysctl.d/99-ione-vpn.conf <<SYSCTL
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
# Harden against common attacks
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
SYSCTL
sysctl --system >/dev/null

cat > "$WG_DIR/$WG_IF.conf" <<EOF
# IONE VPN – WireGuard server configuration
# Generated by deploy/wireguard_setup.sh – DO NOT EDIT manually.
# Peers are appended automatically by the backend API.

[Interface]
Address    = $SERVER_SUBNET
ListenPort = $WG_PORT
PrivateKey = $SERVER_PRIVATE_KEY
# SaveConfig = false (default) – wg-quick will NOT overwrite this file
# on shutdown. The backend API manages peers via wg syncconf/wg set.
SaveConfig = false
# MTU 1420 prevents fragmentation across most ISPs
MTU        = 1420

# NAT – forward VPN traffic through the internet interface.
# PostUp/PostDown run as root when the interface comes up/down.
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; \
           iptables -A FORWARD -o %i -j ACCEPT; \
           iptables -t nat -A POSTROUTING -o $ETH_IF -j MASQUERADE; \
           ip6tables -A FORWARD -i %i -j ACCEPT; \
           ip6tables -A FORWARD -o %i -j ACCEPT; \
           ip6tables -t nat -A POSTROUTING -o $ETH_IF -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; \
           iptables -D FORWARD -o %i -j ACCEPT; \
           iptables -t nat -D POSTROUTING -o $ETH_IF -j MASQUERADE; \
           ip6tables -D FORWARD -i %i -j ACCEPT; \
           ip6tables -D FORWARD -o %i -j ACCEPT; \
           ip6tables -t nat -D POSTROUTING -o $ETH_IF -j MASQUERADE
EOF

chmod 600 "$WG_DIR/$WG_IF.conf"

# ─── Enable & start WireGuard ────────────────────────────────────────────────
info "Starting WireGuard interface $WG_IF..."
systemctl enable --now "wg-quick@$WG_IF"
systemctl restart ufw || true
wg show "$WG_IF"

# ─── Print values needed for .env ────────────────────────────────────────────
info "========================================================"
info " Copy these values into backend/.env:"
info "   WG_SERVER_PRIVATE_KEY=$SERVER_PRIVATE_KEY"
info "   WG_SERVER_PUBLIC_KEY=$SERVER_PUBLIC_KEY"
info "   WG_SERVER_ENDPOINT=${DROPLET_IP}:${WG_PORT}"
info "   SERVER_IP=$DROPLET_IP"
info "========================================================"
